### ISSUE TITLE
Crash añadiendo un temporizador con 0 horas

### ISSUE THREAD

**Issue by xorguy** [Hortelanos/SafeTimer#2]
Hola. 
Con versión 1.0.2 si se añade un temporizador nuevo a 0 horas y se inicia la aplicación se cierra y al volver a abrirla la cuenta es negativa. 

Saludos.

**Comment by asiergmorato** [comment]
Hola Daniel!

Muchas gracias por avisarnos. Lo revisamos.

**Comment by asiergmorato** [comment]
Resuelto en la versión 1.1.
